// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `cdp` plugin's OWN CUE schema — the typed plugin_input for the `cdp`
// Chrome-DevTools check verb. It is the SINGLE SOURCE for this plugin's params,
// used two ways (the same contract core `spec` and the http plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `cdp:` step's plugin_input against #CdpInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `cdp: <method>` step (scalar sugar) or `cdp: {method: …, tab: …}`
// (map form) desugars to the INTERNAL plugin/plugin_input envelope, and every
// cdp-exclusive modifier lives HERE — the former core #CdpMethod enum is this
// def's `method` field, and the former shared #Op `method` HTTP-method modifier
// (which `raw` used for the CDP protocol method name) is RENAMED `http_method`
// (the input's `method` key is the VERB method). The shared assertion matchers
// (exit_status/stdout/stderr) and the general `timeout` stay on core #Op, read
// off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type CdpInput struct {
	// method — the cdp method to dispatch (the former core #CdpMethod enum; also
	// the scalar-sugar primary: `cdp: <method>`).
	Method string `yaml:"method,omitempty" json:"method"`

	// action — start|stop|status for a session (session). session start begins
	// capturing the CDP screencast (Page.startScreencast) at fps into an MJPEG stream
	// (the host-side detached recorder); session stop finalizes it to the evidence row.
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	// fps — the screencast frame rate for session (default 5).
	Fps int `yaml:"fps,omitempty" json:"fps,omitempty"`

	// tab — the target tab: a 1-based page index or a DevTools UUID.
	Tab string `yaml:"tab,omitempty" json:"tab,omitempty"`

	// expression — the JavaScript expression `eval` evaluates.
	Expression string `yaml:"expression,omitempty" json:"expression,omitempty"`

	// url — the page URL `open` navigates to.
	URL string `yaml:"url,omitempty" json:"url,omitempty"`

	// selector — the CSS selector (coords/wait/click/type; pierces shadow DOM).
	Selector string `yaml:"selector,omitempty" json:"selector,omitempty"`

	// text — the text `type`/`spa-type` types.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// x / y — desktop-absolute coordinates (spa-click/spa-mouse).
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// button — the mouse button for spa-click (default left).
	Button string `yaml:"button,omitempty" json:"button,omitempty"`

	// key — the named key `spa-key` presses.
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// combo — the key combo `spa-key-combo` sends (e.g. "ctrl+t").
	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	// query — the optional filter `axtree` matches accessibility nodes against.
	Query string `yaml:"query,omitempty" json:"query,omitempty"`

	// http_method — the raw CDP protocol method `raw` calls (e.g.
	// "Page.captureScreenshot"; RENAMED from the former shared #Op `method`
	// modifier — `method` here is the VERB method).
	HttpMethod string `yaml:"http_method,omitempty" json:"http_method,omitempty"`

	// params — the JSON params blob `raw` passes to the protocol method.
	Params string `yaml:"params,omitempty" json:"params,omitempty"`

	// artifact — the host path `screenshot` writes the PNG to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform — the
	// post-run artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	// session — the DETACHED host-side recorder (Cutover E, E-3): `cdp: session` starts
	// the plugin's OWN binary in recorder mode through the runner's generic
	// background-session service (plugin-check's verb:session seam). The recorder
	// re-dials the tab's CDP WebSocket (the plugin's existing browser venue),
	// captures Page.startScreencast frames at fps into state_dir/frames.mjpeg (each
	// event's JPEG base64 lands as-is — no re-encode), and on SIGTERM finalizes with
	// the FINAL marker + the evidence row.json. tab selects the captured tab
	// (default "1" — the first page tab). venue/phase are stamped into the row.
	SessionId string `yaml:"session_id,omitempty" json:"session_id,omitempty"`

	StateDir string `yaml:"state_dir,omitempty" json:"state_dir,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir (verb-agnostic;
	// the provider appends its own filename/extension).
	ArtifactDir string `yaml:"artifact_dir,omitempty" json:"artifact_dir,omitempty"`

	LogDir string `yaml:"log_dir,omitempty" json:"log_dir,omitempty"`

	Venue string `yaml:"venue,omitempty" json:"venue,omitempty"`

	Phase string `yaml:"phase,omitempty" json:"phase,omitempty"`
}
